# Maintainer tool, not part of the plugin: writes the German .po files from the table below; then run
#   for l in de de_Informal; do msgfmt -o pretix_btcpay/locale/$l/LC_MESSAGES/django.mo pretix_btcpay/locale/$l/LC_MESSAGES/django.po; done
# de uses the formal "Sie", de_Informal the informal "du", as pretix does. Run from the repository root.
T = [
 ("A Greenfield API key limited to the receiving store, with exactly these permissions: btcpay.store.cancreateinvoice, btcpay.store.canviewinvoices and btcpay.store.webhooks.canmodifywebhooks, and btcpay.store.cancreatenonapprovedpullpayments only if refunds are created in BTCPay. Keys with more are refused.",
  "Ein Greenfield-API-Schlüssel nur für den empfangenden Store, mit genau diesen Rechten: btcpay.store.cancreateinvoice, btcpay.store.canviewinvoices und btcpay.store.webhooks.canmodifywebhooks, dazu btcpay.store.cancreatenonapprovedpullpayments nur, wenn Erstattungen in BTCPay angelegt werden. Schlüssel mit mehr Rechten werden abgelehnt.", None),
 ("Create refunds in BTCPay", "Erstattungen in BTCPay anlegen", None),
 ("Off by default: refunds are then done by hand in BTCPay and recorded in pretix. On, the first refund of a payment in pretix creates a BTCPay pull payment that the buyer claims and someone approves in BTCPay; further ones of the same payment are done by hand. The API key then also needs btcpay.store.cancreatenonapprovedpullpayments.",
  "Standardmäßig aus: Erstattungen macht das Team dann von Hand in BTCPay und trägt sie in pretix ein. An: Die erste Erstattung einer Zahlung in pretix legt ein Pull Payment in BTCPay an, das die Käuferin oder der Käufer abholt und jemand in BTCPay freigibt; weitere derselben Zahlung gehen von Hand. Der API-Schlüssel braucht dann auch btcpay.store.cancreatenonapprovedpullpayments.", None),
 ("Refunds in BTCPay need Redis or memcached as pretix' cache.", "Erstattungen in BTCPay brauchen Redis oder memcached als Cache von pretix.", None),
 ("This refund was already sent to BTCPay.", "Diese Erstattung ging schon an BTCPay.", None),
 ("A refund of this payment was already sent to BTCPay ({earlier}). Check the pull payments in BTCPay, and do any further refund of this payment there by hand.",
  "Eine Erstattung dieser Zahlung ging schon an BTCPay ({earlier}). Bitte die Pull Payments in BTCPay prüfen und jede weitere Erstattung dieser Zahlung dort von Hand anlegen.", None),
 ("A refund was not sent to BTCPay, because an earlier refund of the same payment went there. Check BTCPay and do it there by hand.",
  "Eine Erstattung ging nicht an BTCPay, weil schon eine frühere derselben Zahlung dort ist. Bitte in BTCPay prüfen und sie dort von Hand anlegen.", None),
 ("Refunds in BTCPay need the permission btcpay.store.cancreatenonapprovedpullpayments.", "Erstattungen in BTCPay brauchen das Recht btcpay.store.cancreatenonapprovedpullpayments.", None),
 ("only if refunds are created in BTCPay: someone approves each payout there", "nur, wenn Erstattungen in BTCPay angelegt werden: Jede Auszahlung gibt dort jemand frei", None),
 ("The API key is not allowed to create refunds (btcpay.store.cancreatenonapprovedpullpayments).", "Der API-Schlüssel darf keine Erstattungen anlegen (btcpay.store.cancreatenonapprovedpullpayments).", None),
 ("The webhook is being registered right now. Please save again in a minute.", "Der Webhook wird gerade eingerichtet. Bitte in einer Minute noch einmal speichern.", None),
 ("This payment can not be continued. Please start the payment again.", "Diese Zahlung lässt sich nicht fortsetzen. Bitte starten Sie die Zahlung neu.", "Diese Zahlung lässt sich nicht fortsetzen. Bitte starte die Zahlung neu."),
 ("A BTCPay refund was created; the buyer has to claim it and the team to approve it in BTCPay.", "Eine Erstattung wurde in BTCPay angelegt; die Käuferin oder der Käufer muss sie abholen, und das Team gibt sie in BTCPay frei.", None),
 ("BTCPay did not answer while creating a refund. Check in BTCPay whether a pull payment with this name exists before trying again.", "BTCPay hat beim Anlegen einer Erstattung nicht geantwortet. Bitte in BTCPay nachsehen, ob es ein Pull Payment mit diesem Namen gibt, bevor es jemand noch einmal versucht.", None),
 ("The order was marked paid after its confirmed BTCPay payment.", "Die Bestellung wurde nachträglich als bezahlt markiert, passend zu ihrer bestätigten BTCPay-Zahlung.", None),
 ("The BTCPay payment arrived, but the order could not be marked paid because its seats are gone. Add quota or return the money.", "Die BTCPay-Zahlung ist angekommen, aber die Bestellung ließ sich nicht als bezahlt markieren, weil ihre Plätze vergeben sind. Kontingent erhöhen oder das Geld zurückzahlen.", None),
 ("Keys with any other permission, or for other stores, are refused: they could spend or change more than this plugin needs.", "Schlüssel mit anderen Rechten oder für andere Stores werden abgelehnt: Mit ihnen ließe sich mehr ausgeben oder ändern, als das Plugin braucht.", None),
 ("Money beyond the amount of another BTCPay payment of this order, on the same invoice:", "Geld über den Betrag einer anderen BTCPay-Zahlung dieser Bestellung hinaus, auf derselben Rechnung:", None),
 ("Booked as overpayment", "Als Überzahlung gebucht", None),
 ("Send this link to the buyer. They enter their own Bitcoin address or Lightning invoice there, and someone approves the payout in BTCPay; once BTCPay has paid it out, mark this refund as done.", "Diesen Link an die Käuferin oder den Käufer schicken. Dort trägt sie oder er eine eigene Bitcoin-Adresse oder Lightning-Rechnung ein, und jemand gibt die Auszahlung in BTCPay frei; sobald BTCPay ausgezahlt hat, die Erstattung als erledigt markieren.", None),
 ("BTCPay did not answer while creating this refund. Check in BTCPay whether a pull payment with this name exists before trying again:", "BTCPay hat beim Anlegen dieser Erstattung nicht geantwortet. Bitte in BTCPay nachsehen, ob es ein Pull Payment mit diesem Namen gibt, bevor es jemand noch einmal versucht:", None),
 # (msgid, de, de_informal or None = same)
 ("BTCPay Server", "BTCPay Server", None),
 ("Bitcoin / Lightning Network", "Bitcoin / Lightning Network", None),
 ("You have not yet configured your BTCPay Server URL, API key or store ID.", "Die Adresse von BTCPay Server, der API-Schlüssel oder die Store-ID fehlen noch.", None),
 ("BTCPay Server URL", "Adresse von BTCPay Server", None),
 ("The base URL of your BTCPay Server instance, e.g. https://btcpay.example.com", "Die Adresse Ihrer BTCPay-Server-Instanz, etwa https://btcpay.example.com", "Die Adresse deiner BTCPay-Server-Instanz, etwa https://btcpay.example.com"),
 ("BTCPay Server API key", "API-Schlüssel für BTCPay Server", None),
 ("Store ID", "Store-ID", None),
 ("The ID of the BTCPay Server store that receives the payments.", "Die ID des Stores in BTCPay Server, der die Zahlungen empfängt.", None),
 ("Confirmations before an on-chain payment counts", "Bestätigungen, bis eine On-Chain-Zahlung zählt", None),
 ("1 confirmation (recommended)", "1 Bestätigung (empfohlen)", None),
 ("2 confirmations", "2 Bestätigungen", None),
 ("6 confirmations", "6 Bestätigungen", None),
 ("Lightning payments count at once. Zero confirmations are not offered: an unconfirmed transaction can still be replaced.", "Lightning-Zahlungen zählen sofort. Null Bestätigungen gibt es nicht: Eine unbestätigte Transaktion lässt sich noch ersetzen.", None),
 ("Invoice expiration (minutes)", "Laufzeit einer Rechnung (Minuten)", None),
 ("An invoice never runs longer than the payment deadline of its order, and not longer than this. The exchange rate is fixed for as long as the invoice runs.", "Eine Rechnung läuft nie länger als die Zahlungsfrist ihrer Bestellung und nicht länger als hier angegeben. So lange gilt der Kurs.", None),
 ("Payment method name", "Name der Zahlungsart", None),
 ("The name of the payment method that is shown to your customers during checkout.", "So heißt die Zahlungsart für Ihre Kundinnen und Kunden beim Bezahlen.", "So heißt die Zahlungsart für deine Kundinnen und Kunden beim Bezahlen."),
 ("The BTCPay Server URL has to use https.", "Die Adresse von BTCPay Server muss mit https beginnen.", None),
 ("BTCPay Server did not accept this API key at this URL.", "BTCPay Server unter dieser Adresse hat den API-Schlüssel nicht angenommen.", None),
 ("The API key lacks these permissions for the store: {perms}", "Dem API-Schlüssel fehlen diese Rechte für den Store: {perms}", None),
 ("The API key has more rights than it needs ({perms}). Please create a key with only the permissions listed below.", "Der API-Schlüssel hat mehr Rechte, als er braucht ({perms}). Bitte einen Schlüssel nur mit den unten genannten Rechten anlegen.", None),
 ("The store ID is unknown to BTCPay Server, or the key is not allowed to manage its webhooks.", "BTCPay Server kennt die Store-ID nicht, oder der Schlüssel darf dessen Webhooks nicht verwalten.", None),
 ("This payment has expired. Please start the payment again.", "Diese Zahlung ist abgelaufen. Bitte starten Sie die Zahlung neu.", "Diese Zahlung ist abgelaufen. Bitte starte die Zahlung neu."),
 ("We had trouble creating your payment. Please try again and get in touch with us if this problem persists.", "Wir konnten Ihre Zahlung nicht anlegen. Bitte versuchen Sie es noch einmal und melden Sie sich bei uns, wenn das Problem bleibt.", "Wir konnten deine Zahlung nicht anlegen. Bitte versuch es noch einmal und melde dich bei uns, wenn das Problem bleibt."),
 ("To pay for your order, please visit the following page: {url}", "Bezahlen können Sie Ihre Bestellung hier: {url}", "Bezahlen kannst du deine Bestellung hier: {url}"),
 ("This payment has already been received.", "Diese Zahlung ist schon angekommen.", None),
 ("This payment is already being processed and can not be canceled any more.", "Diese Zahlung ist schon unterwegs und lässt sich nicht mehr abbrechen.", None),
 ("Part of this payment has already arrived. Please get in touch with us.", "Ein Teil dieser Zahlung ist schon angekommen. Bitte melden Sie sich bei uns.", "Ein Teil dieser Zahlung ist schon angekommen. Bitte melde dich bei uns."),
 ("This payment has no BTCPay invoice to refund.", "Zu dieser Zahlung gibt es keine BTCPay-Rechnung, die sich erstatten ließe.", None),
 ("BTCPay Server could not create the refund: please do it in BTCPay.", "BTCPay Server konnte die Erstattung nicht anlegen: bitte direkt in BTCPay erstatten.", None),
 ("Unexpected answer from BTCPay Server.", "Unerwartete Antwort von BTCPay Server.", None),
 ("Refund for order {code}", "Erstattung für Bestellung {code}", None),
 # signals.py
 ("A BTCPay invoice was created.", "Eine BTCPay-Rechnung wurde angelegt.", None),
 ("BTCPay has seen the payment; it is waiting for confirmation.", "BTCPay hat die Zahlung gesehen und wartet auf die Bestätigung.", None),
 ("BTCPay received only part of the amount. The rest has to be returned from BTCPay.", "BTCPay hat nur einen Teil des Betrags erhalten. Das Erhaltene muss aus BTCPay zurückgezahlt werden.", None),
 ("BTCPay received more than the amount. The difference has to be returned.", "BTCPay hat mehr als den Betrag erhalten. Die Differenz muss zurückgezahlt werden.", None),
 ("BTCPay received the payment after the invoice expired. Check in BTCPay; marking the invoice as settled there confirms the payment.", "BTCPay hat die Zahlung erst nach Ablauf der Rechnung erhalten. Bitte in BTCPay prüfen; wird die Rechnung dort als bezahlt markiert, gilt die Zahlung als bestätigt.", None),
 ("A BTCPay administrator set the invoice status by hand.", "Jemand hat den Status der Rechnung in BTCPay von Hand gesetzt.", None),
 ("BTCPay marked an invoice as invalid after pretix had confirmed the payment. Please check this order by hand.", "BTCPay hat eine Rechnung als ungültig markiert, nachdem pretix die Zahlung bestätigt hatte. Bitte diese Bestellung von Hand prüfen.", None),
 ("Money arrived on a BTCPay invoice that had expired or was marked invalid. Check it in BTCPay: mark it as settled to confirm the payment, or return the money.",
  "Auf einer abgelaufenen oder als ungültig markierten BTCPay-Rechnung ist Geld angekommen. Bitte in BTCPay prüfen: als bezahlt markieren, um die Zahlung zu bestätigen, oder das Geld zurückzahlen.", None),
 ("BTCPay settled an invoice of a payment that was already refunded.", "BTCPay hat eine Rechnung zu einer schon erstatteten Zahlung als bezahlt gemeldet.", None),
 ("The order could not be kept reserved while the payment confirms.", "Die Bestellung ließ sich nicht reserviert halten, bis die Zahlung bestätigt ist.", None),
 ("The payment was dropped; the order has its old payment deadline again.", "Die Zahlung kam nie an; die Bestellung hat wieder ihre alte Zahlungsfrist.", None),
 ("Another open BTCPay payment of this paid order was cancelled.", "Eine weitere offene BTCPay-Zahlung dieser bezahlten Bestellung wurde abgebrochen.", None),
 ("A BTCPay invoice did not match its payment and was ignored.", "Eine BTCPay-Rechnung passte nicht zu ihrer Zahlung und wurde übergangen.", None),
 ("The BTCPay webhook was registered.", "Der Webhook in BTCPay wurde eingerichtet.", None),
 # templates
 ("Your payment has arrived and is waiting for confirmation by the Bitcoin network. This usually takes about ten minutes; you do not have to do anything. Your order stays reserved in the meantime.",
  "Ihre Zahlung ist angekommen und wartet auf die Bestätigung im Bitcoin-Netz. Das dauert meist etwa zehn Minuten; Sie müssen nichts tun. Ihre Bestellung bleibt so lange reserviert.",
  "Deine Zahlung ist angekommen und wartet auf die Bestätigung im Bitcoin-Netz. Das dauert meist etwa zehn Minuten; du musst nichts tun. Deine Bestellung bleibt so lange reserviert."),
 ("Your payment is still pending.", "Ihre Zahlung steht noch aus.", "Deine Zahlung steht noch aus."),
 ("Pay now", "Jetzt bezahlen", None),
 ("The payment page shows a QR code for the Lightning Network and an on-chain address. This page updates on its own once the payment arrives.",
  "Die Zahlungsseite zeigt einen QR-Code für das Lightning Network und eine On-Chain-Adresse. Diese Seite aktualisiert sich von selbst, sobald die Zahlung ankommt.", None),
 ("BTCPay invoice", "BTCPay-Rechnung", None),
 ("Status", "Status", None),
 ("Amount", "Betrag", None),
 ("Paid", "Bezahlt", None),
 ("BTCPay Server could not be reached.", "BTCPay Server war nicht erreichbar.", None),
 ("Last known:", "Zuletzt bekannt:", None),
 ("Needs attention", "Braucht Aufmerksamkeit", None),
 ("No BTCPay invoice has been created for this payment yet.", "Zu dieser Zahlung gibt es noch keine BTCPay-Rechnung.", None),
 ("BTCPay pull payment", "BTCPay-Pull-Payment", None),
 ("Claim link for the buyer", "Link zum Abholen für die Käuferin oder den Käufer", None),
 ("Payments go to a BTCPay Server store over the Greenfield API. Create an API key in BTCPay under Account → API keys, limited to the receiving store, with exactly these permissions:",
  "Die Zahlungen gehen über die Greenfield-API an einen Store in BTCPay Server. Den API-Schlüssel in BTCPay unter „Account → API keys“ anlegen, beschränkt auf den empfangenden Store, mit genau diesen Rechten:", None),
 ("required", "nötig", None),
 ("Saving checks the key and registers this webhook on the store:", "Beim Speichern wird der Schlüssel geprüft und dieser Webhook im Store eingerichtet:", None),
 ("registered", "eingerichtet", None),
 ("If webhooks get lost, the periodic task of pretix (pretix cron) asks BTCPay about open invoices every few minutes. Make sure it runs.",
  "Gehen Webhooks verloren, fragt die regelmäßige Aufgabe von pretix (pretix cron) alle paar Minuten bei BTCPay nach offenen Rechnungen. Sie muss laufen.", None),
 ("You pay in Bitcoin, over the Lightning Network or on-chain. After you submit your order, you are taken to the payment page.",
  "Sie zahlen in Bitcoin, über das Lightning Network oder on-chain. Nach dem Bestellen kommen Sie zur Zahlungsseite.",
  "Du zahlst in Bitcoin, über das Lightning Network oder on-chain. Nach dem Bestellen kommst du zur Zahlungsseite."),
 ("After you submit your order, you are taken to the payment page, where you can pay over the Lightning Network or on-chain. Your order is paid as soon as the payment is confirmed.",
  "Nach dem Bestellen kommen Sie zur Zahlungsseite; dort zahlen Sie über das Lightning Network oder on-chain. Bezahlt ist Ihre Bestellung, sobald die Zahlung bestätigt ist.",
  "Nach dem Bestellen kommst du zur Zahlungsseite; dort zahlst du über das Lightning Network oder on-chain. Bezahlt ist deine Bestellung, sobald die Zahlung bestätigt ist."),
]
def esc(s): return s.replace('\\','\\\\').replace('"','\\"')
for lang, idx in (("de", 1), ("de_Informal", 2)):
    out = ['msgid ""', 'msgstr ""', '"Project-Id-Version: pretix-btcpayserver\\n"', '"MIME-Version: 1.0\\n"',
           '"Content-Type: text/plain; charset=UTF-8\\n"', '"Content-Transfer-Encoding: 8bit\\n"', f'"Language: {lang}\\n"', '']
    for row in T:
        msg = row[idx] if idx == 1 or row[2] is None else row[2]
        if idx == 2 and row[2] is None: msg = row[1]
        out += [f'msgid "{esc(row[0])}"', f'msgstr "{esc(msg)}"', '']
    open(f"pretix_btcpay/locale/{lang}/LC_MESSAGES/django.po", "w").write("\n".join(out))
print(len(T), "Einträge")
